apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data
  labels:
    app: jenkins
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
